#!/usr/bin/env python3

# pebble sensor mask
DATA_CHANNEL_GPS = 0x1
DATA_CHANNEL_SNR = 0x2
DATA_CHANNEL_VBAT = 0x4
DATA_CHANNEL_DEVINFO = 0x6
DATA_CHANNEL_GAS = 0X10
DATA_CHANNEL_TEMP = 0x20
DATA_CHANNEL_PRESSURE = 0x40
DATA_CHANNEL_HUMIDITY = 0X80
DATA_CHANNEL_ENV_SENSOR = 0xf0
DATA_CHANNEL_TEMP2 = 0x100
DATA_CHANNEL_GYROSCOPE = 0x200
DATA_CHANNEL_ACCELEROMETER = 0x400
DATA_CHANNEL_CUSTOM_MOTION = 0x800
DATA_CHANNEL_ACTION_SENSOR = 0xf00
DATA_CHANNEL_LIGHT_SENSOR = 0x1000

PEBBLE_CONTRACT_MAIN_NET = 0
PEBBLE_CONTRACT_TEST_NET = 1