/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "package.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(PedometerData, PedometerData, AUTO)


PB_BIND(SensorConfig, SensorConfig, AUTO)


PB_BIND(SensorState, SensorState, AUTO)


PB_BIND(SensorConfirm, SensorConfirm, AUTO)


PB_BIND(BinPackage, BinPackage, 2)


PB_BIND(ConfirmPackage, ConfirmPackage, 2)




